membersrvc:
  image: hyperledger/fabric-membersrvc:x86_64-0.6.1-preview
  ports:
    - 7054:7054
  environment:
    - MEMBERSRVC_CA_ACA_ENABLED=true
    - MEMBERSRVC_LOGGING_LEVEL=DEBUG
#  volumes:
#    - ./blockchain/membersrvc.yaml:/opt/gopath/src/github.com/hyperledger/fabric/membersrvc/membersrvc.0.6.yaml
  command: membersrvc

vp0:
  extends:
    file: compose-defaults.yml
    service: vp
  ports:
    - 7050:7050
    - 7051:7051
    - 7053:7053
  environment:
    - CORE_PEER_ID=vp0
    - CORE_PEER_DISCOVERY_PERIOD=1s
    - CORE_PEER_DISCOVERY_TOUCHPERIOD=1s
    - CORE_SECURITY_ENROLLID=test_vp0
    - CORE_SECURITY_ENROLLSECRET=MwYpmSRjupbT
  links:
    - membersrvc

fabric-app:
  image: cesarev/fabric-boilerplate:v1-javascript
  ports:
    - 3000:3000
    - 8080:8080
  tty: true
  links:
    - membersrvc
    - vp0
  volumes:
    - ./api:/usr/src/app/api
    - ./auth:/usr/src/app/auth
    - ./bin:/usr/src/app/bin
    - ./blockchain:/usr/src/app/blockchain
    - ./client/app:/usr/src/app/client/app
    - ./client/assets/css:/usr/src/app/client/assets/css
    - ./client/assets/images:/usr/src/app/client/assets/images
    - ./client/assets/package.json:/usr/src/app/client/assets/package.json
    - ./client/assets/index.html:/usr/src/app/client/assets/index.html
    - ./services:/usr/src/app/services
    - ./src/build-chaincode/data:/usr/src/app/src/build-chaincode/data
    - ./src/build-chaincode/invoke:/usr/src/app/src/build-chaincode/invoke
    - ./src/build-chaincode/query:/usr/src/app/src/build-chaincode/query
    - ./src/build-chaincode/utils:/usr/src/app/src/build-chaincode/utils
    - ./src/build-chaincode/chaincode.go:/usr/src/app/src/build-chaincode/chaincode.go
    - ./testdata:/usr/src/app/testdata
    - ./utils:/usr/src/app/utils
    - ./package.json:/usr/src/app/package.json
    - ./app.js:/usr/src/app/app.js
    - ./config.js:/usr/src/app/config.js
    - ./nodemon.json:/usr/src/app/nodemon.json
    - ./routes.js:/usr/src/app/routes.js
  command: bash -c "sleep 8; npm run clean | npm run build-css | node ./bin/www"
#vp1:
#  extends:
#    file: compose-defaults.yml
#    service: vp
#  environment:
#    - CORE_PEER_ID=vp1
#    - CORE_PEER_DISCOVERY_ROOTNODE=vp0:7051
#    - CORE_SECURITY_ENROLLID=test_vp1
#    - CORE_SECURITY_ENROLLSECRET=5wgHK9qqYaPy
#  links:
#    - vp0
#    - membersrvc
#
#    activate for testing in a simulated bluemix blockchain service environment
#vp2:
#  extends:
#    file: compose-defaults.yml
#    service: vp
#  environment:
#    - CORE_PEER_ID=vp2
#    - CORE_PEER_DISCOVERY_ROOTNODE=vp1:7051
#    - CORE_SECURITY_ENROLLID=test_vp2
#    - CORE_SECURITY_ENROLLSECRET=vQelbRvja7cJ
#  links:
#    - vp1
#    - membersrvc
#
#vp3:
#  extends:
#    file: compose-defaults.yml
#    service: vp
#  environment:
#    - CORE_PEER_ID=vp3
#    - CORE_PEER_DISCOVERY_ROOTNODE=vp2:7051
#    - CORE_SECURITY_ENROLLID=test_vp3
#    - CORE_SECURITY_ENROLLSECRET=9LKqKH5peurL
#  links:
#    - vp2
#    - membersrvc
